"""Create each department's own PostgreSQL database and point that
department's service at it.

    python -m app.sandbox.provision_postgres          (from backend/)

For every department (see ``app.department_api.service.DEPARTMENT_DATABASES``)
this creates the database if it does not exist -- it never drops, empties or
alters an existing database -- and writes ``backend/.env.departments`` with
one ``SANDBOX_DB_URL_<DEPARTMENT>`` per department. Only the department
services read that file; SANGAM's own backend never does.

For local development the department databases live on the same PostgreSQL
server as SANGAM (separate databases, separate URLs). In a real deployment
each would be a different server and credential. Credentials are never
printed.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url

from app.department_api.service import DEPARTMENT_DATABASES, DEPARTMENT_ENV_FILE

BACKEND = Path(__file__).resolve().parents[2]


def _server_url():
    url = os.getenv("DEPARTMENT_DB_SERVER_URL")
    if not url:
        for line in (BACKEND / ".env").read_text(encoding="utf-8").splitlines():
            if line.startswith("DATABASE_URL="):
                url = line.split("=", 1)[1].strip()
    if not url:
        raise SystemExit("Set DEPARTMENT_DB_SERVER_URL (or DATABASE_URL in backend/.env).")
    return make_url(url)


def provision() -> dict:
    server = _server_url()
    reserved = {server.database, "postgres", "template0", "template1"}
    admin = create_engine(server.set(database="postgres"), isolation_level="AUTOCOMMIT")
    created, existing = [], []
    with admin.connect() as connection:
        present = {row[0] for row in connection.execute(text("SELECT datname FROM pg_database"))}
        for key, database in DEPARTMENT_DATABASES.items():
            if database in reserved:
                raise SystemExit(f"Refusing to use reserved database name {database!r} for {key}.")
            if database in present:
                existing.append(database)
            else:
                connection.execute(text(f'CREATE DATABASE "{database}"'))
                created.append(database)
    lines = ["# Department databases (one per department). Read only by the department",
             "# API services (app.department_api.service). Generated by",
             "# python -m app.sandbox.provision_postgres -- do not commit.",
             "DEPARTMENT_SANDBOX_AUTO_SEED=true"]
    for key, database in DEPARTMENT_DATABASES.items():
        lines.append(f"SANDBOX_DB_URL_{key.upper()}={server.set(database=database).render_as_string(hide_password=False)}")
    DEPARTMENT_ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {"created": created, "alreadyExisted": existing, "envFile": str(DEPARTMENT_ENV_FILE.name)}


if __name__ == "__main__":
    result = provision()
    print(f"created: {result['created']}")
    print(f"already existed (left untouched): {result['alreadyExisted']}")
    print(f"wrote {result['envFile']} (credentials not shown)")
    sys.exit(0)
