import { useEffect, useState } from 'react';
import { api } from '../api';
import { languageText } from '../i18n';
import SangamMark from './SangamMark';

export default function Navbar({ page, setPage, citizen, language = 'en', onLanguageChange, onLogout, onNotificationSelect }) {
  const [notifications, setNotifications] = useState([]); const [open, setOpen] = useState(false); const role = citizen?.role; const t = languageText(language);
  const links = role === 'CITIZEN' ? [['dashboard', t.dashboard], ['discovery', t.services], ['tracking', t.tracking]] : role === 'OFFICER' ? [['officer', 'Officer Desk']] : role === 'ADMIN' ? [['health', 'Integration Health'], ['audit', 'Audit Lineage']] : [];
  useEffect(() => { if (!citizen?.role) { setNotifications([]); return undefined; } let active = true; const load = () => api.notifications(citizen.role).then(result => { if (active) setNotifications(result.notifications || []); }).catch(() => {}); load(); const timer = setInterval(load, 4000); return () => { active = false; clearInterval(timer); }; }, [citizen?.role, citizen?.userId]);
  async function selectNotification(notification) { try { await api.markNotificationRead(notification.notificationId); setNotifications(items => items.map(item => item.notificationId === notification.notificationId ? { ...item, read: true } : item)); } catch { /* backend remains authoritative */ } setOpen(false); onNotificationSelect?.(notification); }
  const unread = notifications.filter(item => !item.read).length;
  return <><header className="tricolor"/><nav><button className="brand brand-button" onClick={() => citizen && setPage(role === 'CITIZEN' ? 'dashboard' : role === 'OFFICER' ? 'officer' : 'health')} aria-label="Sangam home"><SangamMark size={34}/><div><strong>SANGAM</strong><small>Federated Government Interoperability Platform</small></div></button><div className="navlinks">{citizen && links.map(([key, label]) => <button key={key} className={page === key ? 'active' : ''} onClick={() => setPage(key)}>{label}</button>)}</div>{citizen && <div className="nav-tools"><button className="language-switch" onClick={() => onLanguageChange?.(language === 'en' ? 'mr' : 'en')} aria-label="Change language">{language === 'en' ? 'मराठी' : 'English'}</button><div className="notification-wrap"><button className="notification-button" onClick={() => setOpen(!open)} aria-label={language === 'en' ? 'Notifications' : 'सूचना'}>♧ <span className="notification-label">{language === 'en' ? 'Notifications' : 'सूचना'}</span>{unread > 0 && <span className="notification-badge">{unread}</span>}</button>{open && <div className="notification-panel"><div className="notification-heading">{language === 'en' ? 'Notifications' : 'सूचना'} <small>{unread ? `${unread} unread` : 'All caught up'}</small></div>{notifications.length === 0 ? <p className="muted">{language === 'en' ? 'No notifications yet.' : 'सध्या कोणत्याही सूचना नाहीत.'}</p> : notifications.slice(0, 8).map(notification => <button className={`notification-item ${notification.read ? '' : 'unread'}`} key={notification.notificationId} onClick={() => selectNotification(notification)}><b>{notification.title}</b><span>{notification.message}</span><small>{new Date(notification.createdAt).toLocaleString()}</small></button>)}</div>}</div><div className="signed"><b>{citizen.name}</b><small>{role} · {citizen.userId || citizen.citizenId}</small></div>{onLogout && <button className="logout" onClick={onLogout}>{t.signOut}</button>}</div>}</nav></>;
}
