"""Phase 6F2 Task E: persisted citizen notifications.

A separate write-through Postgres table (CitizenNotificationRow /
citizen_notifications) from the legacy officer/admin notification_manager,
because that legacy table's persist_state() snapshot deliberately excludes
anything tied to a PostgreSQL-authoritative application (see
CitizenNotificationRow's docstring) -- so it could never durably carry a
notification generated by the Phase 6B+ Auto-Fill/submission flows this task
needs to notify on.
"""
from __future__ import annotations

import os
import unittest
from unittest.mock import patch

from sqlalchemy.orm import Session

from tests.catalog_fixture import non_demo_citizens
from app.api.citizen_routes import ApplySchemeRequest, AutoFillDecision, RequirementUpload, apply_to_scheme, auto_fill_requirement, submit_citizen_application, upload_requirement_document
from app.api.notification_routes import citizen_notifications, mark_notification_read
from app.core.persistence import ApplicationRow, CitizenNotificationRow, CitizenRow, DocumentRow, engine, seed_catalog, seed_requirement_catalog
from fastapi import HTTPException
from types import SimpleNamespace


def _user(citizen_id: str) -> dict:
    return {"userId": citizen_id, "citizenId": citizen_id, "name": "Test Citizen", "role": "CITIZEN"}


def _fake_request():
    return SimpleNamespace(state=SimpleNamespace())


import itertools

# See test_identity_auto_fill.py's identical helper for why this doesn't
# always return the same citizen. This module claims offsets 30-44.
_citizen_offsets = itertools.count(30)


def _real_citizen_id() -> str:
    with Session(engine) as session:
        return non_demo_citizens(session).offset(next(_citizen_offsets)).limit(1).first().citizen_id


def setUpModule():
    with patch.dict(os.environ, {"SANGAM_SEED_CATALOG": "true"}):
        seed_catalog()
        seed_requirement_catalog()
    # Defensive cleanup: this module's real citizens (offsets 30-44) are
    # shared fixtures across separate full-suite runs, not fresh per run --
    # an interrupted earlier run (or one from before per-test offsets were
    # introduced) can leave a leftover SUBMITTED application behind, which
    # would make apply_to_scheme's idempotent reuse hand a later test an
    # already-submitted application instead of a fresh one.
    with Session(engine) as session:
        offset_citizen_ids = [
            row.citizen_id for row in
            non_demo_citizens(session).offset(30).limit(20).all()
        ]
        if offset_citizen_ids:
            session.query(DocumentRow).filter(DocumentRow.citizen_id.in_(offset_citizen_ids)).delete(synchronize_session=False)
            session.query(ApplicationRow).filter(ApplicationRow.citizen_id.in_(offset_citizen_ids)).delete(synchronize_session=False)
            session.query(CitizenNotificationRow).filter(CitizenNotificationRow.citizen_id.in_(offset_citizen_ids)).delete(synchronize_session=False)
            session.commit()


class CitizenNotificationTests(unittest.TestCase):
    def setUp(self):
        self._created_app_ids: list[str] = []
        self._citizen_ids: list[str] = []

    def tearDown(self):
        with Session(engine) as session:
            if self._created_app_ids:
                session.query(DocumentRow).filter(DocumentRow.app_id.in_(self._created_app_ids)).delete(synchronize_session=False)
                session.query(ApplicationRow).filter(ApplicationRow.app_id.in_(self._created_app_ids)).delete(synchronize_session=False)
            if self._citizen_ids:
                session.query(CitizenNotificationRow).filter(CitizenNotificationRow.citizen_id.in_(self._citizen_ids)).delete(synchronize_session=False)
            session.commit()

    def _apply(self, citizen_id: str, scheme_id: str = "SCH-MH-2026") -> dict:
        self._citizen_ids.append(citizen_id)
        application = apply_to_scheme(ApplySchemeRequest(schemeId=scheme_id), _fake_request(), user=_user(citizen_id))
        if application.get("status") == "SUBMITTED":
            # A stray already-submitted application from this shared real
            # citizen fixture (left behind by some other, unrelated test
            # elsewhere in the suite) would otherwise make apply_to_scheme's
            # idempotent reuse hand back a locked application here -- clear
            # it and re-apply once rather than let that show up as a
            # confusing downstream 409 in this test.
            with Session(engine) as session:
                session.query(DocumentRow).filter_by(app_id=application["appId"]).delete(synchronize_session=False)
                session.query(ApplicationRow).filter_by(app_id=application["appId"]).delete(synchronize_session=False)
                session.commit()
            application = apply_to_scheme(ApplySchemeRequest(schemeId=scheme_id), _fake_request(), user=_user(citizen_id))
        self._created_app_ids.append(application["appId"])
        return application

    def test_table_is_actually_persisted_not_an_in_memory_fake(self):
        citizen_id = _real_citizen_id()
        self._citizen_ids.append(citizen_id)
        application = self._apply(citizen_id)
        auto_fill_requirement(application["appId"], "DOMICILE_PROOF", AutoFillDecision(decision="ACCEPT"), user=_user(citizen_id))
        with Session(engine) as session:
            rows = session.query(CitizenNotificationRow).filter_by(citizen_id=citizen_id).all()
        self.assertTrue(rows)

    def test_document_verified_notification_on_successful_auto_fill(self):
        citizen_id = _real_citizen_id()
        application = self._apply(citizen_id)
        auto_fill_requirement(application["appId"], "DOMICILE_PROOF", AutoFillDecision(decision="ACCEPT"), user=_user(citizen_id))
        notes = citizen_notifications(user=_user(citizen_id))["notifications"]
        verified = [n for n in notes if n["type"] == "DOCUMENT_VERIFIED"]
        self.assertEqual(len(verified), 1)
        self.assertIn("Maharashtra Domicile Certificate", verified[0]["message"])
        self.assertEqual(verified[0]["applicationId"], application["appId"])
        self.assertEqual(verified[0]["requirementCode"], "DOMICILE_PROOF")
        self.assertFalse(verified[0]["read"])

    def test_action_required_notification_when_citizen_declines_auto_fill(self):
        citizen_id = _real_citizen_id()
        application = self._apply(citizen_id)
        auto_fill_requirement(application["appId"], "CASTE_PROOF", AutoFillDecision(decision="REJECT"), user=_user(citizen_id))
        notes = citizen_notifications(user=_user(citizen_id))["notifications"]
        action_needed = [n for n in notes if n["type"] == "ACTION_REQUIRED"]
        self.assertEqual(len(action_needed), 1)
        self.assertIn("Please upload it manually", action_needed[0]["message"])

    def test_no_duplicate_notification_on_repeated_no_op_auto_fill(self):
        """Retrying Auto-Fill on an already-satisfied requirement must not
        spam a second 'document verified' notification."""
        citizen_id = _real_citizen_id()
        application = self._apply(citizen_id)
        auto_fill_requirement(application["appId"], "DOMICILE_PROOF", AutoFillDecision(decision="ACCEPT"), user=_user(citizen_id))
        auto_fill_requirement(application["appId"], "DOMICILE_PROOF", AutoFillDecision(decision="ACCEPT"), user=_user(citizen_id))
        notes = citizen_notifications(user=_user(citizen_id))["notifications"]
        verified = [n for n in notes if n["type"] == "DOCUMENT_VERIFIED"]
        self.assertEqual(len(verified), 1)

    def test_document_verified_notification_on_manual_upload(self):
        citizen_id = _real_citizen_id()
        application = self._apply(citizen_id)
        upload_requirement_document(
            application["appId"], "CASTE_PROOF",
            RequirementUpload(title="My caste certificate", content="synthetic demo upload content"),
            user=_user(citizen_id),
        )
        notes = citizen_notifications(user=_user(citizen_id))["notifications"]
        verified = [n for n in notes if n["type"] == "DOCUMENT_VERIFIED" and n["requirementCode"] == "CASTE_PROOF"]
        self.assertEqual(len(verified), 1)

    def test_application_submitted_notification_fires_once_not_on_idempotent_resubmit(self):
        citizen_id = _real_citizen_id()
        application = self._apply(citizen_id)
        for code in ("IDENTITY", "INCOME_PROOF", "CASTE_PROOF", "DOMICILE_PROOF", "ACADEMIC_RECORD", "BANK_DETAILS"):
            auto_fill_requirement(application["appId"], code, AutoFillDecision(decision="ACCEPT"), user=_user(citizen_id))
        submit_citizen_application(application["appId"], user=_user(citizen_id))
        submit_citizen_application(application["appId"], user=_user(citizen_id))  # idempotent resubmit
        notes = citizen_notifications(user=_user(citizen_id))["notifications"]
        submitted = [n for n in notes if n["type"] == "APPLICATION_SUBMITTED"]
        self.assertEqual(len(submitted), 1)

    def test_mark_notification_read(self):
        citizen_id = _real_citizen_id()
        application = self._apply(citizen_id)
        auto_fill_requirement(application["appId"], "DOMICILE_PROOF", AutoFillDecision(decision="ACCEPT"), user=_user(citizen_id))
        notification_id = citizen_notifications(user=_user(citizen_id))["notifications"][0]["notificationId"]
        result = mark_notification_read(notification_id, user=_user(citizen_id))
        self.assertTrue(result["read"])
        notes = citizen_notifications(user=_user(citizen_id))["notifications"]
        self.assertTrue(next(n for n in notes if n["notificationId"] == notification_id)["read"])

    def test_a_citizen_cannot_see_or_mark_another_citizens_notification(self):
        citizen_id = _real_citizen_id()
        application = self._apply(citizen_id)
        auto_fill_requirement(application["appId"], "DOMICILE_PROOF", AutoFillDecision(decision="ACCEPT"), user=_user(citizen_id))
        notification_id = citizen_notifications(user=_user(citizen_id))["notifications"][0]["notificationId"]

        other_notes = citizen_notifications(user=_user("SOME-OTHER-CITIZEN"))["notifications"]
        self.assertFalse(any(n["notificationId"] == notification_id for n in other_notes))

        with self.assertRaises(HTTPException) as ctx:
            mark_notification_read(notification_id, user=_user("SOME-OTHER-CITIZEN"))
        self.assertEqual(ctx.exception.status_code, 404)


# Remove every runtime row (applications, consents, documents, notifications,
# provider jobs/incidents) this module leaves in the shared database.
from tests.catalog_fixture import guard_module_runtime_state  # noqa: E402
guard_module_runtime_state(globals())


if __name__ == "__main__":
    unittest.main()
