"""Add persisted citizen notifications table (Phase 6F2 Task E).

A separate table from the legacy `notifications` table (NotificationRow):
persist_state()'s snapshot of that legacy table deliberately excludes any
notification whose applicationId belongs to a PostgreSQL-authoritative
application (protected_app_ids), so it can never durably carry a
notification generated by the Phase 6B+ authoritative Auto-Fill/submission
flows. This table is written through directly (like documents/consents),
never via that snapshot path, so it needs no such exclusion.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0015_citizen_notifications"
down_revision = "0014_documents"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "citizen_notifications",
        sa.Column("notification_id", sa.String(160), primary_key=True),
        sa.Column("citizen_id", sa.String(120), nullable=False),
        sa.Column("notification_type", sa.String(60), nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        # application_id/requirement_code are deliberately not foreign keys,
        # matching the existing documents/audit_entries convention for
        # unconstrained references to in-flight workflow state.
        sa.Column("application_id", sa.String(120), nullable=True),
        sa.Column("requirement_code", sa.String(120), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", postgresql.JSONB(), nullable=False, server_default="{}"),
    )
    op.create_index("ix_citizen_notifications_citizen_id", "citizen_notifications", ["citizen_id"])
    op.create_index("ix_citizen_notifications_application_id", "citizen_notifications", ["application_id"])
    op.create_index("ix_citizen_notifications_is_read", "citizen_notifications", ["is_read"])


def downgrade():
    op.drop_index("ix_citizen_notifications_is_read", table_name="citizen_notifications")
    op.drop_index("ix_citizen_notifications_application_id", table_name="citizen_notifications")
    op.drop_index("ix_citizen_notifications_citizen_id", table_name="citizen_notifications")
    op.drop_table("citizen_notifications")
