"""legacy_baseline

Revision ID: 62ebc0864a84
Revises: 0001_catalog
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '62ebc0864a84'
down_revision = '0001_catalog'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('app_id', sa.String(length=120), nullable=False),
    sa.Column('citizen_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_index(op.f('ix_applications_citizen_id'), 'applications', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('audit_entries',
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=120), nullable=True),
    sa.Column('consent_id', sa.String(length=120), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('sequence')
    )
    op.create_index(op.f('ix_audit_entries_consent_id'), 'audit_entries', ['consent_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_correlation_id'), 'audit_entries', ['correlation_id'], unique=False)
    op.create_table('counters',
    sa.Column('counter_key', sa.String(length=120), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('counter_key')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.String(length=120), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('occurred_at', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_app_id'), 'events', ['app_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_table('integration_state',
    sa.Column('system', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('system')
    )
    op.create_table('mock_department_state',
    sa.Column('state_key', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('state_key')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=180), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_accounts',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_accounts_role'), 'user_accounts', ['role'], unique=False)
    op.create_table('conflict_reviews',
    sa.Column('review_id', sa.String(length=160), nullable=False),
    sa.Column('app_id', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.app_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_conflict_reviews_app_id'), 'conflict_reviews', ['app_id'], unique=False)
    op.create_table('consents',
    sa.Column('consent_id', sa.String(length=120), nullable=False),
    sa.Column('citizen_id', sa.String(length=120), nullable=False),
    sa.Column('app_id', sa.String(length=120), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.app_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('consent_id')
    )
    op.create_index(op.f('ix_consents_app_id'), 'consents', ['app_id'], unique=False)
    op.create_index(op.f('ix_consents_citizen_id'), 'consents', ['citizen_id'], unique=False)
    op.create_table('dependencies',
    sa.Column('dependency_id', sa.String(length=160), nullable=False),
    sa.Column('app_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.app_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dependency_id')
    )
    op.create_index(op.f('ix_dependencies_app_id'), 'dependencies', ['app_id'], unique=False)
    op.create_index(op.f('ix_dependencies_status'), 'dependencies', ['status'], unique=False)
    op.create_table('entity_reviews',
    sa.Column('review_id', sa.String(length=160), nullable=False),
    sa.Column('app_id', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.app_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_entity_reviews_app_id'), 'entity_reviews', ['app_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=120), nullable=False),
    sa.Column('recipient_user_id', sa.String(length=120), nullable=False),
    sa.Column('app_id', sa.String(length=120), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.app_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_app_id'), 'notifications', ['app_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_table('workflow_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.app_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_history_app_id'), 'workflow_history', ['app_id'], unique=False)
    op.create_index(op.f('ix_providers_department_id'), 'providers', ['department_id'], unique=False)
    op.create_index(op.f('ix_scheme_requirements_requirement_code'), 'scheme_requirements', ['requirement_code'], unique=False)
    op.create_index(op.f('ix_scheme_requirements_scheme_id'), 'scheme_requirements', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_service_catalog_provider_id'), 'service_catalog', ['provider_id'], unique=False)
    op.create_index(op.f('ix_service_catalog_requirement_code'), 'service_catalog', ['requirement_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_catalog_requirement_code'), table_name='service_catalog')
    op.drop_index(op.f('ix_service_catalog_provider_id'), table_name='service_catalog')
    op.drop_index(op.f('ix_scheme_requirements_scheme_id'), table_name='scheme_requirements')
    op.drop_index(op.f('ix_scheme_requirements_requirement_code'), table_name='scheme_requirements')
    op.drop_index(op.f('ix_providers_department_id'), table_name='providers')
    op.drop_index(op.f('ix_workflow_history_app_id'), table_name='workflow_history')
    op.drop_table('workflow_history')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_app_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_entity_reviews_app_id'), table_name='entity_reviews')
    op.drop_table('entity_reviews')
    op.drop_index(op.f('ix_dependencies_status'), table_name='dependencies')
    op.drop_index(op.f('ix_dependencies_app_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index(op.f('ix_consents_citizen_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_app_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_conflict_reviews_app_id'), table_name='conflict_reviews')
    op.drop_table('conflict_reviews')
    op.drop_index(op.f('ix_user_accounts_role'), table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('mock_department_state')
    op.drop_table('integration_state')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_app_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('counters')
    op.drop_index(op.f('ix_audit_entries_correlation_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_consent_id'), table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_citizen_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
