import { useState } from 'react';

export default function ServiceDiscoveryPage({ discovery, onDiscover, navigate }) {
  const [busy, setBusy] = useState(false);
  async function run(timeout = false) { setBusy(true); await onDiscover(timeout); setBusy(false); }
  return <main className="container">
    <div className="page-title"><div><p className="eyebrow">{discovery?.service?.name || 'Configured service'} · Requirement analysis</p><h1>Federated record discovery</h1><p>We look up metadata from participating departments—no files are copied into this portal.</p></div><div><button className="outline" onClick={() => run(true)}>Test resilience</button> <button className="primary" onClick={() => run()}>{busy ? 'Probing sources…' : 'Scan linked departments'}</button></div></div>
    {discovery?.resilienceBanner && <div className="alert">{discovery.resilienceBanner}</div>}
    {discovery && <>
      <div className="card"><table><thead><tr><th>Requirement</th><th>What you need to do</th><th>Status</th></tr></thead><tbody>{discovery.requirements.map(r => <tr key={r.requirementCode}><td><b>{r.displayLabel || r.requirementCode}</b></td><td>{r.userAction || '—'}</td><td><span className={`status ${String(r.status).toLowerCase()}`}>{r.status}</span></td></tr>)}</tbody></table>{discovery.conflicts.length > 0 && <div className="alert danger">{discovery.conflicts.map(conflict => <div key={`${conflict.field}-${conflict.status}`}>{conflict.message || 'Additional review is required.'}</div>)}</div>}<div className="actions"><button className="primary" onClick={() => navigate('consent')}>Continue to purpose-bound consent</button></div></div>
      {discovery.mappingEvidence?.length > 0 && <div className="card"><p className="eyebrow">Interoperability evidence</p><h2>Hybrid canonical schema mapping</h2><p>Deterministic canonical rules remain authoritative. Local metadata-only suggestions are shown separately and never silently verified.</p><table><thead><tr><th>Source system</th><th>Source field</th><th>Canonical field</th><th>Mapping method</th><th>Confidence / evidence</th><th>Provenance</th></tr></thead><tbody>{discovery.mappingEvidence.map((mapping, index) => <tr key={`${mapping.sourceSystem}-${mapping.sourceField}-${mapping.canonicalField}-${index}`}><td>{mapping.sourceSystem}<small>{mapping.adapter}</small></td><td><code>{mapping.sourceField}</code></td><td><code>{mapping.canonicalField}</code></td><td>{mapping.mappingMode}<small>{mapping.mappingType}</small></td><td>{Math.round(mapping.confidence * 100)}%<small>{mapping.evidence}</small></td><td>{mapping.sourceRecordId || '—'}</td></tr>)}</tbody></table></div>}
      {discovery.semanticMappingEvidence?.length > 0 && <div className="card"><p className="eyebrow">Technical mapping suggestions · simulated schemas</p><h2>AI-assisted semantic suggestions</h2><p>Local deterministic token/alias inference is used for schema metadata only. Medium and low confidence items require officer/admin review.</p><table><thead><tr><th>Source field</th><th>Canonical field</th><th>Method</th><th>Confidence</th><th>Evidence / review</th></tr></thead><tbody>{discovery.semanticMappingEvidence.map((mapping, index) => <tr key={`${mapping.sourceSystem}-${mapping.sourceField}-${index}`}><td><code>{mapping.sourceField}</code><small>{mapping.sourceSystem}</small></td><td><code>{mapping.canonicalField || 'UNRESOLVED'}</code></td><td>{mapping.mappingMode}</td><td>{mapping.confidenceLevel} · {Math.round(mapping.confidence * 100)}%</td><td>{mapping.evidence}<small>{mapping.reviewStatus || (mapping.humanReviewRequired ? 'Human review required' : 'Deterministic/high-confidence result')}</small></td></tr>)}</tbody></table></div>}
    </>}
  </main>
}
