import { useState } from 'react';

export default function ServiceDiscoveryPage({ discovery, onDiscover, navigate }) {
  const [busy, setBusy] = useState(false);
  async function run(timeout = false) { setBusy(true); await onDiscover(timeout); setBusy(false); }
  return <main className="container">
    <div className="page-title"><div><p className="eyebrow">SCH-MH-2026 · Requirement analysis</p><h1>Federated record discovery</h1><p>We look up metadata from participating departments—no files are copied into this portal.</p></div><div><button className="outline" onClick={() => run(true)}>Test resilience</button> <button className="primary" onClick={() => run()}>{busy ? 'Probing sources…' : 'Scan linked departments'}</button></div></div>
    {discovery?.resilienceBanner && <div className="alert">{discovery.resilienceBanner}</div>}
    {discovery && <>
      <div className="card"><table><thead><tr><th>Requirement</th><th>Source / connector</th><th>Record</th><th>Resolution</th><th>Status</th></tr></thead><tbody>{discovery.requirements.map(r => <tr key={r.code}><td><b>{r.code.replace('_', ' ')}</b></td><td>{r.source}<small>{r.adapter}</small></td><td>{r.recordId || '—'}</td><td>{r.resolution ? `${r.resolution.status} · ${Math.round(r.resolution.score * 100)}%` : '—'}</td><td><span className={`status ${r.status.toLowerCase()}`}>{r.status}</span>{r.action && <small>{r.action}</small>}</td></tr>)}</tbody></table>{discovery.conflicts.length > 0 && <div className="alert danger">{discovery.conflicts.map(conflict => <div key={`${conflict.canonicalField}-${conflict.detectedAt}`}>Conflict detected for <b>{conflict.canonicalField}</b> across {conflict.sources.map(source => source.sourceSystem).join(' and ')}.</div>)}</div>}<div className="actions"><button className="primary" onClick={() => navigate('consent')}>Continue to purpose-bound consent</button></div></div>
      {discovery.mappingEvidence?.length > 0 && <div className="card"><p className="eyebrow">Interoperability evidence</p><h2>Deterministic canonical schema mapping</h2><p>Different department field names are normalized into shared canonical fields. This prototype uses explicit rules, not AI-generated mappings.</p><table><thead><tr><th>Source system</th><th>Source field</th><th>Canonical field</th><th>Transformation</th><th>Provenance</th></tr></thead><tbody>{discovery.mappingEvidence.map((mapping, index) => <tr key={`${mapping.sourceSystem}-${mapping.sourceField}-${mapping.canonicalField}-${index}`}><td>{mapping.sourceSystem}<small>{mapping.adapter}</small></td><td><code>{mapping.sourceField}</code></td><td><code>{mapping.canonicalField}</code></td><td>{mapping.mappingType}<small>{mapping.certainty} · {Math.round(mapping.confidence * 100)}%</small></td><td>{mapping.sourceRecordId || '—'}</td></tr>)}</tbody></table></div>}
    </>}
  </main>
}
